# Generated by Django 3.1.3 on 2021-06-17 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Voicer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_animes', models.IntegerField(default=16)),
                ('votes', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=150)),
                ('animes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animes_tour', to='Voicer.anime')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tour', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(max_length=50)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_votes', to='Voicer.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tour', 'vote_type')},
            },
        ),
    ]
