# Generated by Django 3.2.4 on 2021-07-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voicer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='quantity',
            field=models.IntegerField(default=2),
        ),
    ]
