# Generated by Django 3.1.3 on 2021-06-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voicer', '0002_tournament_uservotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='animes',
        ),
        migrations.AddField(
            model_name='tournament',
            name='animes',
            field=models.ManyToManyField(to='Voicer.Anime'),
        ),
    ]
